[project]
name = 'Insurance-Pool'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Insurance-Pool]
path = 'contracts/Insurance-Pool.clar'
clarity_version = 3
epoch = 3.1

[contracts.MultiSig-Claims]
path = 'contracts/MultiSig-Claims.clar'
clarity_version = 3
epoch = 3.1

[contracts.Risk-Assessment]
path = 'contracts/Risk-Assessment.clar'
clarity_version = 3
epoch = 3.1

[contracts.coverage-tiers]
path = 'contracts/coverage-tiers.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
